WhiteNoise/Models/Departamento/DepartamentoFormModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WhiteNoise.Models.Departamento
{
    public class DepartamentoFormModel
    {
        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Informe uma descrição.")]
        public string? Descricao { get; set; }

        public Guid Id { get; set; }

    }
}

WhiteNoise/Models/Departamento/DepartamentoGridModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WhiteNoise.Models.Departamento
{
    public class DepartamentoGridModel
    {
        [Display(Name = "Descrição")]
        public string? Descricao { get; set; }

        public Guid Id { get; set; }

    }
}

WhiteNoise/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WhiteNoise.Application.Interfaces.Services;
using WhiteNoise.Domain.Entities;
using WhiteNoise.Models.Departamento;

namespace WhiteNoise.Controllers
{
    public class DepartamentoController : BaseController
    {
        #region Private Fields
        private readonly IDepartamentoService _departamentoService;
        private readonly INotyfService _notyf;
        private readonly IMapper _mapper;


        #endregion

        #region Constructors
        public DepartamentoController(IMapper mapper, 
            IDepartamentoService departamentoService,
            INotyfService notyf)
        {
            _departamentoService = departamentoService;
            _notyf = notyf;
            _mapper = mapper;
        }

        #endregion

        #region Public Methods
        public async Task<IActionResult> Index()
        {
            var departamentos = await _departamentoService.ObterTodos();
            var departamentosGridModel = _mapper.Map<List<DepartamentoGridModel>>(departamentos);
            return View(departamentosGridModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var departamento = await _departamentoService.ObterPorId(id);
            var departamentoFormModel = _mapper.Map<DepartamentoFormModel>(departamento);
            return View(departamentoFormModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DepartamentoFormModel departamentoFormModel)
        {
            if (!ModelState.IsValid)
            {
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(departamentoFormModel);

            }
            var departamento = _mapper.Map<Departamento>(departamentoFormModel);
            await _departamentoService.Adicionar(departamento);
            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var departamento = await _departamentoService.ObterPorId(id);

            if (departamento == null)
                return NotFound();

            var departamentoFormModel = _mapper.Map<DepartamentoFormModel>(departamento);

            return View(departamentoFormModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, DepartamentoFormModel departamentoFormModel)
        {
            if (id != departamentoFormModel.Id)
                return NotFound();

            if (!ModelState.IsValid)
            {
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(departamentoFormModel);
            }

            try
            {
                var departamento = _mapper.Map<Departamento>(departamentoFormModel);
                await _departamentoService.Atualizar(departamento);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao salvar as informações.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));            
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var departamento = await _departamentoService.ObterPorId(id);

            if (departamento == null)
            {
                return NotFound();
            }

            var departamentoFormModel = _mapper.Map<DepartamentoFormModel>(departamento);

            return View(departamentoFormModel);

        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                await _departamentoService.Remover(id);
            }
            catch (Exception ex)
            {
                _notyf.Error("Ocorreu um erro ao deletar o registro.");
                return BadRequest(ex.Message);
            }

            _notyf.Success("As informações foram deletadas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

WhiteNoise/Views/Departamento/Create.cshtml
@using WhiteNoise.Domain.Entities
@using WhiteNoise.Domain.Enums
@model WhiteNoise.Models.Departamento.DepartamentoFormModel

@{
    ViewData["Title"] = "Cadastrar Departamento";
}

<div>
    <h2>Novo Departamento</h2>
    <form asp-action="Create" method="post" autocomplete="off">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row col-12">
            <div class="form-group col-6">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
        </div>

        <div class="d-flex justify-content-end w-25">
            <button type="submit" class="btn btn-info w-50 me-2">
                <i class="bi bi-check-circle me-1"></i> Salvar
            </button>
            <a asp-action="Index" class="btn btn-outline-secondary ml-2 w-50">
                <i class="bi bi-arrow-left me-1"></i> Voltar
            </a>
        </div>
    </form>
</div>

WhiteNoise/Views/Departamento/Delete.cshtml
@using WhiteNoise.Models.Departamento
@model DepartamentoFormModel

@{
    ViewData["Title"] = "Deletar Departamento";
}

<div>
    <h3>Deletar Departamento</h3>

    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Tem certeza desta ação?</h4>
        <p>Esta ação é irreversível e removerá permanentemente o registro selecionado.</p>
    </div>

    <div>
        <label asp-for="Descricao"></label>
        <input asp-for="Descricao" disabled class="form-control" />
    </div>

    <form asp-controller="Departamento" asp-action="DeleteConfirmed" method="post">
        <input type="hidden" asp-for="Id" />
        <div>
            <input type="submit" value="Deletar" class="btn btn-danger" />
            <a class="btn btn-secondary" asp-controller="Departamento" asp-action="Index">Cancelar</a>
        </div>
    </form>
</div>

WhiteNoise/Views/Departamento/Details.cshtml
@model WhiteNoise.Models.Departamento.DepartamentoFormModel

<div>
    <h2>Detalhes do Departamento</h2>
    <div>
        <dl class="row">
            <dt class="col-sm-2">Descrição</dt>
            <dd class="col-sm-10">@Model.Descricao</dd>
        </dl>

        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-info">Editar</a>
        <a asp-action="Index" class="btn btn-secondary">Voltar</a>
    </div>
</div>

WhiteNoise/Views/Departamento/Edit.cshtml
@using WhiteNoise.Domain.Enums
@using WhiteNoise.Models.Departamento
@model DepartamentoFormModel

@{
    ViewData["Title"] = "Editar Departamento";
}

<div>
    <h3>Editar Estado Clínico</h3>

    <form asp-action="Edit" asp-controller="Departamento" asp-route-id="@Model.Id" method="post" autocomplete="off">
        <input type="hidden" name="_method" value="PUT" />

        <div class="form-group">
            <label asp-for="Descricao" class="control-label"></label>
            <input asp-for="Descricao" class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>

        <div>
            <input type="submit" value="Confirmar" class="btn btn-success" />
            <a class="btn btn-secondary" asp-controller="Departamento" asp-action="Index">Cancelar</a>
        </div>
    </form>
</div>

WhiteNoise/Views/Departamento/Index.cshtml
@using WhiteNoise.Models.Departamento

@model IEnumerable<DepartamentoGridModel>

@{
    ViewData["Title"] = "Listagem de Departamentos";
}

<div>
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="fw-bold mb-0">@ViewData["Title"]</h2>
        <a class="btn btn-lg btn-primary rounded-pill shadow-sm"
           asp-controller="Departamento" asp-action="Create">
            <i class="bi bi-plus-lg me-2"></i>Adicionar Novo
        </a>
    </div>

    <table-grid controller="Departamento" allow-sorting="true" items="@Model"></table-grid>
</div>