WhiteNoise/Models/Shared/ContadorViewModel.cs
namespace WhiteNoise.Models.Shared
{
    public class ContadorViewModel
    {
        public int Contador { get; set; }
    }
}

WhiteNoise/Controllers/LeitoController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WhiteNoise.Application.Interfaces.Services;
using WhiteNoise.Domain.Entities;
using WhiteNoise.Models.Leito;

namespace WhiteNoise.Controllers
{
    public class LeitoController : BaseController
    {
        #region Private Fields
        private readonly ILeitoService _leitoService;
        private readonly IDepartamentoService _departamentoService;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;

        #endregion

        #region Constructors
        public LeitoController(IMapper mapper, 
            ILeitoService leitoService,
            INotyfService notyf,
            IDepartamentoService departamentoService)
        {
            _departamentoService = departamentoService;
            _leitoService = leitoService;
            _notyf = notyf;
            _mapper = mapper;
        }

        #endregion

        #region Private Methods
        private async Task PopularDepartamentos(LeitoFormModel model)
        {
            var departamentos = await _departamentoService.ObterTodos();
            model.Departamentos = new SelectList(departamentos, "Id", "Descricao", model.DepartamentoId);
        }

        #endregion

        #region Public Methods
        public async Task<IActionResult> Index()
        {
            var leitos = await _leitoService.ObterTodos();
            var leitosGridModel = _mapper.Map<List<LeitoGridModel>>(leitos);
            return View(leitosGridModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var leito = await _leitoService.ObterPorId(id);
            var leitoGridModel = _mapper.Map<LeitoGridModel>(leito);
            return View(leitoGridModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new LeitoFormModel();
            await PopularDepartamentos(model);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(LeitoFormModel leitoFormModel)
        {
            if (!ModelState.IsValid)
            {
                await PopularDepartamentos(leitoFormModel);
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(leitoFormModel);
            }

            try
            {
                var leito = _mapper.Map<Leito>(leitoFormModel);

                await _leitoService.Adicionar(leito);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao salvar as informações.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var leito = await _leitoService.ObterPorId(id);

            if (leito == null)
                return NotFound();

            var leitoFormModel = _mapper.Map<LeitoFormModel>(leito);
            await PopularDepartamentos(leitoFormModel);
            return View(leitoFormModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, LeitoFormModel leitoFormModel)
        {
            if (id != leitoFormModel.Id)
                return NotFound();

            if (!ModelState.IsValid)
            {
                await PopularDepartamentos(leitoFormModel);
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(leitoFormModel);
            }

            try
            {
                var leito = _mapper.Map<Leito>(leitoFormModel);
                await _leitoService.Atualizar(leito);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao salvar as informações.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var leito = await _leitoService.ObterPorId(id);

            if (leito == null)
            {
                return NotFound();
            }

            var leitoGridModel = _mapper.Map<LeitoGridModel>(leito);

            return View(leitoGridModel);

        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                await _leitoService.Remover(id);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao deletar o registro.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram deletadas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

WhiteNoise/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WhiteNoise.Application.Interfaces.Services;
using WhiteNoise.Domain.Entities;
using WhiteNoise.Models.Paciente;

namespace WhiteNoise.Controllers
{
    public class PacienteController : BaseController
    {
        #region Private Fields
        private readonly IMapper _mapper;
        private readonly IPacienteService _pacienteService;
        private readonly IEstadoClinicoService _estadoClinicoService;
        private readonly INotyfService _notyf;

        #endregion

        #region Constructors
        public PacienteController(IMapper mapper, 
            IPacienteService pacienteService, 
            IEstadoClinicoService estadoClinicoService, 
            INotyfService notyf)
        {
            _mapper = mapper;
            _pacienteService = pacienteService;
            _estadoClinicoService = estadoClinicoService;
            _notyf = notyf;
        }

        #endregion

        #region Private Methods
        private async Task PopularEstadosClinicos(PacienteFormModel model)
        {
            var estados = await _estadoClinicoService.ObterTodos();
            model.EstadosClinicos = new SelectList(estados, "Id", "Descricao", model.EstadoClinicoId);
        }

        #endregion

        #region Public Methods
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var pacientes = await _pacienteService.ObterTodos();
            var pacientesViewModel = _mapper.Map<List<PacienteGridModel>>(pacientes);
            return View(pacientesViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            var paciente = await _pacienteService.ObterPorId(id);
            var pacienteGridModel = _mapper.Map<PacienteGridModel>(paciente);
            return View(pacienteGridModel);
        }

        [HttpGet]
        public async Task<IActionResult> ObterPacientesPorEstadoClinico(Guid? id)
        {
            var paciente = await _pacienteService.ObterPorEstadoClinicoId(id);
            var pacienteFormModel = _mapper.Map<PacienteFormModel>(paciente);
            return View(pacienteFormModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new PacienteFormModel();
            await PopularEstadosClinicos(model);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PacienteFormModel pacienteFormModel)
        {
            if (!ModelState.IsValid)
            {
                await PopularEstadosClinicos(pacienteFormModel);
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(pacienteFormModel);
            }

            var paciente = _mapper.Map<Paciente>(pacienteFormModel);
            
            await _pacienteService.Adicionar(paciente);
            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var paciente = await _pacienteService.ObterPorId(id);

            if (paciente == null)
                return NotFound();

            var pacienteFormModel = _mapper.Map<PacienteFormModel>(paciente);
            await PopularEstadosClinicos(pacienteFormModel);
            return View(pacienteFormModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, PacienteFormModel pacienteFormModel)
        {
            if (id != pacienteFormModel.Id)
                return NotFound();

            if (!ModelState.IsValid)
            {
                await PopularEstadosClinicos(pacienteFormModel);
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(pacienteFormModel);
            }

            try
            {
                var paciente = _mapper.Map<Paciente>(pacienteFormModel);
                await _pacienteService.Atualizar(paciente);
            }

            catch
            {
                _notyf.Error("Ocorreu um erro ao salvar as informações.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var paciente = await _pacienteService.ObterPorId(id);

            if (paciente == null)
            {
                return NotFound();
            }

            var pacienteGridModel = _mapper.Map<PacienteGridModel>(paciente);

            return View(pacienteGridModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                await _pacienteService.Remover(id);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao deletar o registro.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram deletadas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

WhiteNoise/Controllers/ProntuarioController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WhiteNoise.Application.Interfaces.Services;
using WhiteNoise.Domain.Entities;
using WhiteNoise.Models.Prontuario;

namespace WhiteNoise.Controllers
{
    public class ProntuarioController : BaseController
    {
        #region Private Fields
        private readonly IProntuarioService _prontuarioService;
        private readonly INotyfService _notyf;
        private readonly IMapper _mapper;

        #endregion

        #region Constructors
        public ProntuarioController(IMapper mapper, 
            IProntuarioService prontuarioService,
            INotyfService notyf)
        {
            _prontuarioService = prontuarioService;
            _notyf = notyf;
            _mapper = mapper;
        }

        #endregion

        #region Public Methods
        public async Task<IActionResult> Index()
        {
            var prontuario = await _prontuarioService.ObterTodos();
            var prontuarioGridModel = _mapper.Map<List<ProntuarioGridModel>>(prontuario);
            return View(prontuarioGridModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var prontuario = await _prontuarioService.ObterPorId(id);
            var prontuarioGridModel = _mapper.Map<ProntuarioGridModel>(prontuario);
            return View(prontuarioGridModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new ProntuarioFormModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProntuarioFormModel prontuarioFormModel)
        {
            if (!ModelState.IsValid)
            {
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(prontuarioFormModel);
            }
            var prontuario = _mapper.Map<Prontuario>(prontuarioFormModel);

            await _prontuarioService.Adicionar(prontuario);
            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var prontuario = await _prontuarioService.ObterPorId(id);

            if (prontuario == null)
                return NotFound();

            var prontuarioFormModel = _mapper.Map<ProntuarioFormModel>(prontuario);
            return View(prontuarioFormModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, ProntuarioFormModel prontuarioFormModel)
        {
            if (id != prontuarioFormModel.Id)
                return NotFound();

            if (!ModelState.IsValid)
            {
                _notyf.Error("Preencha todas as informações obrigatórias.");
                return View(prontuarioFormModel);
            }

            try
            {
                var prontuario = _mapper.Map<Prontuario>(prontuarioFormModel);
                await _prontuarioService.Atualizar(prontuario);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao salvar as informações.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram salvas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var prontuario = await _prontuarioService.ObterPorId(id);

            if (prontuario == null)
            {
                return NotFound();
            }

            var prontuarioGridModel = _mapper.Map<ProntuarioGridModel>(prontuario);

            return View(prontuarioGridModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                await _prontuarioService.Remover(id);
            }
            catch
            {
                _notyf.Error("Ocorreu um erro ao deletar o registro.");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Success("As informações foram deletadas com sucesso.");
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

WhiteNoise/Shared/ViewComponents/Agendamento/AgendamentoPeriodoViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using WhiteNoise.Infra.Data.Contexts;
using WhiteNoise.Models.Shared;
using WhiteNoise.Shared.Helpers;

namespace WhiteNoise.Shared.ViewComponents.Agendamento
{
    public class AgendamentoPeriodoViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public AgendamentoPeriodoViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke(DateTime? diaInicio = null, DateTime? diaFinal = null)
        {
            var inicio = diaInicio?.Date ?? DateTime.Today;
            var fim = diaFinal?.Date ?? inicio.AddDays(1);

            var totalPorPeriodo = AgendamentoHelper.ObterTotalizadorAgendamentosPorPeriodo(_context, inicio, fim);

            var model = new ContadorViewModel
            {
                Contador = totalPorPeriodo
            };

            return View(model);
        }
    }
}

WhiteNoise/Shared/ViewComponents/Agendamento/AgendamentoPorPeriodoViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using WhiteNoise.Infra.Data.Contexts;
using WhiteNoise.Models.Shared;
using WhiteNoise.Shared.Helpers;

namespace WhiteNoise.Shared.ViewComponents.Agendamento
{
    public class AgendamentoPorPeriodoViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public AgendamentoPorPeriodoViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke(DateTime? diaInicio = null, DateTime? diaFinal = null)
        {
            var inicio = diaInicio?.Date ?? DateTime.Today;
            var fim = diaFinal?.Date ?? inicio.AddDays(1);

            var totalPorPeriodo = AgendamentoHelper.ObterTotalizadorAgendamentosPorPeriodo(_context, inicio, fim);

            var model = new ContadorViewModel
            {
                Contador = totalPorPeriodo
            };

            return View(model);
        }
    }
}

WhiteNoise/Views/Shared/PartialViews/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - WhiteNoise - <a asp-area="" asp-controller="Home" asp-action="Home">Home</a>
        <email dominio="teste.com">renan</email>
    </div>
</footer>

WhiteNoise/Views/Shared/PartialViews/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-info bg-info border-bottom mb-3 pl-3 sticky-top">
        <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index">WhiteNoise</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-person"></i> Nome do Usuário
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Perfil</a>
                        <a class="dropdown-item" href="#">Configurações</a>
                        <div class="dropdown-divider"></div>
                        <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/Index", new { area = "" })" method="post">
                            <button type="submit" class="dropdown-item">Logout</button>
                        </form>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav flex-grow-1 ml-3">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="pacientesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-people me-2"></i> Pacientes
                    </a>
                    <div class="dropdown-menu" aria-labelledby="pacientesDropdown">
                        <a class="dropdown-item" asp-controller="Paciente" asp-action="Create"><i class="bi bi-person-plus me-2"></i> Novo Paciente</a>
                        <a class="dropdown-item" asp-controller="Paciente" asp-action="Index"><i class="bi bi-card-list me-2"></i> Lista de Pacientes</a>
                        <a class="dropdown-item" asp-controller="Prontuario" asp-action="Index"><i class="bi bi-file-medical me-2"></i> Prontuários</a>
                        <a class="dropdown-item" asp-controller="EstadoClinico" asp-action="Index"><i class="bi bi-clipboard-pulse me-2"></i> Estados Clínicos</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="leitosDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-hospital"></i> Internações
                    </a>
                    <div class="dropdown-menu" aria-labelledby="leitosDropdown">
                        <a class="dropdown-item" asp-controller="Internacao" asp-action="Create"><i class="bi bi-plus-circle me-2"></i> Nova Internação</a>
                        <a class="dropdown-item" asp-controller="Internacao" asp-action="Index"><i class="bi bi-clipboard-data me-2"></i> Internações Ativas</a>
                        <a class="dropdown-item" asp-controller="Internacao" asp-action="Historico"><i class="bi bi-journal-text me-2"></i> Histórico de Internações</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="administracaoDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-gear me-2"></i> Administração
                    </a>
                    <div class="dropdown-menu" aria-labelledby="administracaoDropdown">
                        <a class="dropdown-item" asp-controller="Profissional" asp-action="Index"><i class="bi bi-person-badge me-2"></i> Profissionais</a>
                        <a class="dropdown-item" asp-controller="Leito" asp-action="Index"><i class="bi bi-door-open me-2"></i> Leitos</a>
                        <a class="dropdown-item" asp-controller="Departamento" asp-action="Index"><i class="bi bi-building me-2"></i> Departamentos</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="agendamentosDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <i class="bi bi-calendar-check me-2"></i> Agendamentos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="agendamentosDropdown">
                        <a class="dropdown-item" style="white-space: nowrap;" asp-controller="Agendamento" asp-action="Create">
                            <i class="bi bi-journal-plus me-2"></i> Novo Agendamento
                        </a>
                        <a class="dropdown-item" style="white-space: nowrap;" asp-controller="Agendamento" asp-action="Index">
                            <i class="bi bi-card-checklist me-2"></i> Lista de Agendamentos
                        </a>
                        <a class="dropdown-item" style="white-space: nowrap;" asp-controller="Agendamento" asp-action="Calendario">
                            <i class="bi bi-calendar-event me-2"></i> Calendário
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>